/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jFrame;

import javaClass.ValidasiForm;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Daftar_bisnis_baru extends javax.swing.JFrame {

    /**
     * Creates new form Daftar_bisnis_baru
     */
    public Daftar_bisnis_baru() {
        initComponents();
        setLocationRelativeTo(null);
        buatNoRek();
    }
    
    String[] bil = {"1", "2", "3", "4", "5", "6", "7", "8", "9", "0"};
    String noRek = "";
    
    public void buatNoRek(){
        for(int i = 0; i<5; i++){
            int rand = new Random().nextInt(bil.length);
            noRek += bil[rand];
        }
        jTextFieldRekening.setText(noRek);
    }
    
    public void daftarGagal(){
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan dalam pembuatan Nasabah");
    }
    
    public void daftarBerhasil(){
        JOptionPane.showMessageDialog(this, "Nasabah berhasil dibuat");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooserTTL = new com.toedter.calendar.JDateChooser();
        jButtonBack = new javax.swing.JButton();
        jTextFieldRekening = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldAlamat = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButtonDaftar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldJenis = new javax.swing.JTextField();
        jButtonTambah = new javax.swing.JButton();
        jTextFieldKtp = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldSaldo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1366, 768));
        setSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(null);
        getContentPane().add(jDateChooserTTL);
        jDateChooserTTL.setBounds(520, 380, 400, 30);

        jButtonBack.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonBack.setText("Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBack);
        jButtonBack.setBounds(519, 580, 80, 31);

        jTextFieldRekening.setEditable(false);
        jTextFieldRekening.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jTextFieldRekening);
        jTextFieldRekening.setBounds(520, 230, 400, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Jenis Rekening");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(350, 190, 117, 22);

        jTextFieldNama.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jTextFieldNama);
        jTextFieldNama.setBounds(520, 330, 400, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("No. Rekening");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(350, 230, 105, 22);

        jTextFieldAlamat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jTextFieldAlamat);
        jTextFieldAlamat.setBounds(520, 420, 400, 70);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("No. KTP");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(350, 280, 65, 22);

        jButtonDaftar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonDaftar.setText("Daftar");
        jButtonDaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDaftarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDaftar);
        jButtonDaftar.setBounds(610, 580, 90, 31);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Nama");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(350, 330, 45, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("TTL");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(350, 380, 31, 22);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Alamat");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(350, 420, 54, 22);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("Daftar Rekening Baru");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(550, 100, 229, 29);

        jTextFieldJenis.setEditable(false);
        jTextFieldJenis.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldJenis.setText("Bisnis");
        jTextFieldJenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldJenisActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldJenis);
        jTextFieldJenis.setBounds(520, 190, 115, 28);

        jButtonTambah.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonTambah.setText("Tambah Rekening");
        jButtonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTambahActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonTambah);
        jButtonTambah.setBounds(725, 580, 190, 31);

        jTextFieldKtp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jTextFieldKtp);
        jTextFieldKtp.setBounds(520, 280, 400, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Saldo");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(350, 500, 43, 22);

        jTextFieldSaldo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jTextFieldSaldo);
        jTextFieldSaldo.setBounds(520, 500, 400, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        // TODO add your handling code here:
        Dashboard d = new Dashboard();
        d.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonDaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDaftarActionPerformed
        // TODO add your handling code here:
        ValidasiForm validasi = new ValidasiForm(jTextFieldJenis.getText(),
            jTextFieldKtp.getText(), jTextFieldRekening.getText(),
            jTextFieldNama.getText(), jDateChooserTTL.getDate(),
            jTextFieldAlamat.getText(), Integer.parseInt(jTextFieldSaldo.getText()));

        if(validasi.cekFormBisnis()){
            daftarGagal();
        }else{
            validasi.setInputNasabahBaru();
            daftarBerhasil();
        }
    }//GEN-LAST:event_jButtonDaftarActionPerformed

    private void jButtonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTambahActionPerformed
        // TODO add your handling code here:
        Daftar_bisnis tambah = new Daftar_bisnis();
        tambah.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonTambahActionPerformed

    private void jTextFieldJenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldJenisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldJenisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Daftar_bisnis_baru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Daftar_bisnis_baru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Daftar_bisnis_baru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Daftar_bisnis_baru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Daftar_bisnis_baru().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonDaftar;
    private javax.swing.JButton jButtonTambah;
    private com.toedter.calendar.JDateChooser jDateChooserTTL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextFieldAlamat;
    private javax.swing.JTextField jTextFieldJenis;
    private javax.swing.JTextField jTextFieldKtp;
    private javax.swing.JTextField jTextFieldNama;
    private javax.swing.JTextField jTextFieldRekening;
    private javax.swing.JTextField jTextFieldSaldo;
    // End of variables declaration//GEN-END:variables
}
