/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jFrame;

import javaClass.cariNoKtp;
import javaClass.ValidasiForm;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Daftar_biasa extends javax.swing.JFrame {

    /**
     * Creates new form Daftar_biasa
     */
    public Daftar_biasa() {
        initComponents();
        setLocationRelativeTo(null);
        buatNoRek();
    }
    
    String[] bil = {"1", "2", "3", "4", "5", "6", "7", "8", "9", "0"};
    String noRek = "";
    
    public void buatNoRek(){
        for(int i = 0; i<5; i++){
            int rand = new Random().nextInt(bil.length);
            noRek += bil[rand];
        }
        jTextFieldRekening.setText(noRek);
    }
    
    public void daftarGagal(){
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan dalam pembuatan Nasabah");
    }
    
    public void daftarBerhasil(){
        JOptionPane.showMessageDialog(this, "Nasabah berhasil dibuat");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonBack = new javax.swing.JButton();
        jTextFieldRekening = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonDaftar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jDateChooserTTL = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldJenis = new javax.swing.JTextField();
        jButtonCari = new javax.swing.JButton();
        jTextFieldKtp = new javax.swing.JTextField();
        jTextFieldCari = new javax.swing.JTextField();
        jTextFieldAlamat = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldSaldo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1366, 768));
        setSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(null);

        jButtonBack.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonBack.setText("Kembali");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBack);
        jButtonBack.setBounds(550, 610, 140, 31);

        jTextFieldRekening.setEditable(false);
        jTextFieldRekening.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jTextFieldRekening);
        jTextFieldRekening.setBounds(550, 270, 400, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Jenis Rekening");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(350, 230, 120, 22);

        jTextFieldNama.setEditable(false);
        jTextFieldNama.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jTextFieldNama);
        jTextFieldNama.setBounds(550, 370, 400, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("No. Rekening");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(350, 280, 110, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("No. KTP");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(350, 330, 70, 22);

        jButtonDaftar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonDaftar.setText("Daftar");
        jButtonDaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDaftarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDaftar);
        jButtonDaftar.setBounds(780, 610, 170, 31);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Nama");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(350, 380, 50, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("TTL");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(350, 420, 50, 22);

        jDateChooserTTL.setEnabled(false);
        getContentPane().add(jDateChooserTTL);
        jDateChooserTTL.setBounds(550, 420, 400, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Alamat");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(350, 460, 60, 22);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("Daftar Tambah Rekening");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(550, 100, 266, 29);

        jTextFieldJenis.setEditable(false);
        jTextFieldJenis.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldJenis.setText("Biasa");
        getContentPane().add(jTextFieldJenis);
        jTextFieldJenis.setBounds(550, 230, 115, 28);

        jButtonCari.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonCari.setText("Cari");
        jButtonCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCariActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCari);
        jButtonCari.setBounds(760, 190, 90, 31);

        jTextFieldKtp.setEditable(false);
        jTextFieldKtp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldKtp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldKtpActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldKtp);
        jTextFieldKtp.setBounds(550, 320, 400, 40);

        jTextFieldCari.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jTextFieldCari);
        jTextFieldCari.setBounds(550, 190, 200, 30);

        jTextFieldAlamat.setEditable(false);
        jTextFieldAlamat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jTextFieldAlamat);
        jTextFieldAlamat.setBounds(550, 460, 400, 70);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Saldo");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(350, 550, 50, 22);

        jTextFieldSaldo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jTextFieldSaldo);
        jTextFieldSaldo.setBounds(550, 540, 400, 40);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("No KTP");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(350, 190, 60, 22);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        // TODO add your handling code here:
        Dashboard d = new Dashboard();
        d.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonDaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDaftarActionPerformed
        // TODO add your handling code here:
        ValidasiForm validasi = new ValidasiForm(jTextFieldJenis.getText(),
            jTextFieldKtp.getText(), jTextFieldRekening.getText(), jTextFieldNama.getText(),
            jDateChooserTTL.getDate(), jTextFieldAlamat.getText(), Integer.parseInt(jTextFieldSaldo.getText()));

        if(validasi.cekFormBiasa()){
            daftarGagal();
        }else{
            validasi.setInputNasabah();
            daftarBerhasil();
        }
    }//GEN-LAST:event_jButtonDaftarActionPerformed

    private void jButtonCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCariActionPerformed
        // TODO add your handling code here:
        int ktpNasabah = Integer.parseInt(jTextFieldCari.getText());
        
        cariNoKtp dataNasabah = new cariNoKtp();
        dataNasabah.setKtp(ktpNasabah);
        String[] nasabah = dataNasabah.getDataNasabah();
        try{
            jTextFieldKtp.setText(Integer.toString(ktpNasabah));
            jTextFieldNama.setText(nasabah[0]);
            Date ttl = new SimpleDateFormat("MM/dd/yyyy").parse(nasabah[1]);
            jDateChooserTTL.setDate(ttl);
            jTextFieldAlamat.setText(nasabah[2]);
            
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButtonCariActionPerformed

    private void jTextFieldKtpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldKtpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldKtpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Daftar_biasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Daftar_biasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Daftar_biasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Daftar_biasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Daftar_biasa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonCari;
    private javax.swing.JButton jButtonDaftar;
    private com.toedter.calendar.JDateChooser jDateChooserTTL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextFieldAlamat;
    private javax.swing.JTextField jTextFieldCari;
    private javax.swing.JTextField jTextFieldJenis;
    private javax.swing.JTextField jTextFieldKtp;
    private javax.swing.JTextField jTextFieldNama;
    private javax.swing.JTextField jTextFieldRekening;
    private javax.swing.JTextField jTextFieldSaldo;
    // End of variables declaration//GEN-END:variables
}
