/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jFrame;

import javaClass.KoneksiDB;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javaClass.rekBiasa;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form dashboard
     */
    
    public Dashboard() {
        initComponents();
        setLocationRelativeTo(null);
        
        //rekBiasa rekBiasa =  new rekBiasa();
        
        //rekBiasa.setBiayaAdmin(rekBiasa.getBulan(), rekBiasa.getCurrentDate());
        //rekBiasa.setBunga(rekBiasa.getTahun(), rekBiasa.getCurrentDate());
        //rekBisnis.setBiayaAdmin(rekBisnis.getBulan(), rekBisnis.getCurrentDate());
        //rekBisnis.setBunga(rekBisnis.getTahun(), rekBisnis.getCurrentDate());
        //rekBisnis.setPoin(rekBisnis.getTahun(), rekBisnis.getCurrentDate());
        
        int teller_ktp = Login.teller_ktp;
        Connection koneksi;
        PreparedStatement ps;
        
        koneksi = KoneksiDB.getKoneksi();
        String sql = "SELECT * FROM teller WHERE teller_ktp = ?";
        
        try{
            ps = koneksi.prepareStatement(sql);
            ps.setInt(1, teller_ktp);
            ResultSet rs = ps.executeQuery();
            if(rs.next()){
                teller_nama = rs.getString("teller_nama");
                jLabelTeller.setText(teller_nama);
            }else{
                jLabelTeller.setText("Teller tidak ditemukan");
            }
            
            
            
        }catch(SQLException e){
            
        }
    }
    
    public static String teller_nama;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonTeller = new javax.swing.JButton();
        jButtonNasabah = new javax.swing.JButton();
        jButtonDebit = new javax.swing.JButton();
        jButtonKredit = new javax.swing.JButton();
        jButtonLaporan = new javax.swing.JButton();
        jLabelTeller = new javax.swing.JLabel();
        jButtonExit = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1366, 768));
        setSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Dashboard Teller");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(630, 210, 181, 29);

        jButtonTeller.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonTeller.setText("Tambah Teller");
        jButtonTeller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTellerActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonTeller);
        jButtonTeller.setBounds(480, 270, 220, 31);

        jButtonNasabah.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonNasabah.setText("Daftar Nasabah Biasa");
        jButtonNasabah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNasabahActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonNasabah);
        jButtonNasabah.setBounds(480, 320, 220, 31);

        jButtonDebit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonDebit.setText("Penyetoran");
        jButtonDebit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDebitActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDebit);
        jButtonDebit.setBounds(740, 270, 200, 31);

        jButtonKredit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonKredit.setText("Penarikan");
        jButtonKredit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKreditActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonKredit);
        jButtonKredit.setBounds(740, 320, 200, 31);

        jButtonLaporan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonLaporan.setText("Laporan");
        jButtonLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLaporanActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLaporan);
        jButtonLaporan.setBounds(740, 370, 200, 31);

        jLabelTeller.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(jLabelTeller);
        jLabelTeller.setBounds(550, 490, 0, 0);

        jButtonExit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonExit.setText("Exit");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExit);
        jButtonExit.setBounds(660, 440, 110, 31);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Daftar Nasabah Bisnis");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(480, 370, 220, 31);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTellerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTellerActionPerformed
        // TODO add your handling code here:
        Teller teller = new Teller();
        teller.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonTellerActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        // TODO add your handling code here:
        int logout = JOptionPane.showOptionDialog(this, "Apakah anda yakin ingin logout?",
                "LOGOUT", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, 
                null, null, null);
        if(logout == JOptionPane.YES_OPTION){
            Login login = new Login();
            login.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonNasabahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNasabahActionPerformed
        // TODO add your handling code here:
        Daftar_biasa_baru daftarBiasa = new Daftar_biasa_baru();
        daftarBiasa.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonNasabahActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Daftar_bisnis_baru daftarBisnis = new Daftar_bisnis_baru();
        daftarBisnis.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonDebitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDebitActionPerformed
        // TODO add your handling code here:
        Debit d = new Debit();
        d.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonDebitActionPerformed

    private void jButtonKreditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKreditActionPerformed
        // TODO add your handling code here:
        Kredit k = new Kredit();
        k.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonKreditActionPerformed

    private void jButtonLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLaporanActionPerformed
        // TODO add your handling code here:
        Rekening rek = new Rekening();
        rek.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonLaporanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonDebit;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonKredit;
    private javax.swing.JButton jButtonLaporan;
    private javax.swing.JButton jButtonNasabah;
    private javax.swing.JButton jButtonTeller;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelTeller;
    // End of variables declaration//GEN-END:variables
}
