/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jFrame;

import javaClass.CariRekening;
import javaClass.TransaksiRek;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Kredit extends javax.swing.JFrame {
    
    String teller_nama = Dashboard.teller_nama;
    //int teller_ktp = Login.teller_ktp;
    int teller_ktp = 1635;
    int totalTransaksi;

    /**
     * Creates new form Kredit
     */
    public Kredit() {
        initComponents();
        setLocationRelativeTo(null);
        setForm();
    }
    
    public void setForm(){
        jTextFieldTeller.setText(teller_nama);
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd");
        LocalDateTime currentDate = LocalDateTime.now();
        jTextFieldTanggal.setText(dtf.format(currentDate));
    }
    
    public void KreditGagal(){
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan dalam melakukan Penarikan");
    }
    
    public void KreditBerhasil(){
        JOptionPane.showMessageDialog(this, "Proses penarikan berhasil");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jTextFieldSaldo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldKredit = new javax.swing.JTextField();
        jTextFieldCari = new javax.swing.JTextField();
        jButtonProses = new javax.swing.JButton();
        jButtonCari = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButtonBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldTeller = new javax.swing.JTextField();
        jTextFieldNama = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldTanggal = new javax.swing.JTextField();
        jTextFieldJenis = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldSisa = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1366, 768));
        setSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Saldo");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(760, 310, 43, 22);

        jTextFieldSaldo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jTextFieldSaldo);
        jTextFieldSaldo.setBounds(890, 310, 400, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Jumlah Kredit");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(760, 370, 108, 22);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("No. Rekening");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 250, 105, 22);

        jTextFieldKredit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jTextFieldKredit);
        jTextFieldKredit.setBounds(890, 370, 400, 40);

        jTextFieldCari.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jTextFieldCari);
        jTextFieldCari.setBounds(220, 250, 400, 40);

        jButtonProses.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonProses.setText("Proses");
        jButtonProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProsesActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonProses);
        jButtonProses.setBounds(720, 470, 110, 31);

        jButtonCari.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonCari.setText("Cari");
        jButtonCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCariActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCari);
        jButtonCari.setBounds(630, 250, 90, 31);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Teller");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 190, 43, 22);

        jButtonBack.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonBack.setText("Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBack);
        jButtonBack.setBounds(589, 470, 110, 31);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Nama");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 310, 45, 22);

        jTextFieldTeller.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jTextFieldTeller);
        jTextFieldTeller.setBounds(220, 190, 400, 40);

        jTextFieldNama.setEditable(false);
        jTextFieldNama.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jTextFieldNama);
        jTextFieldNama.setBounds(220, 310, 400, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Tanggal");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(760, 190, 63, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Jenis Rekening");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 370, 117, 22);

        jTextFieldTanggal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jTextFieldTanggal);
        jTextFieldTanggal.setBounds(890, 190, 400, 40);

        jTextFieldJenis.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jTextFieldJenis);
        jTextFieldJenis.setBounds(220, 370, 400, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Sisa Penarikan");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(760, 250, 113, 22);

        jTextFieldSisa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jTextFieldSisa);
        jTextFieldSisa.setBounds(890, 250, 400, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProsesActionPerformed
        // TODO add your handling code here:
        TransaksiRek transKre = new TransaksiRek();
        transKre.setTransaksi(Integer.parseInt(jTextFieldCari.getText()));
        totalTransaksi = transKre.getJmlTransaksi();
        
        CariRekening rekNasabah = new CariRekening();
        rekNasabah.setRekNasabah(Integer.parseInt(jTextFieldCari.getText()));
        String dataNasabah[] = rekNasabah.getNasabah();
        String dataRekening[] = rekNasabah.getRekening();
        
        if(dataRekening[3].equals("Biasa")){
            if(jTextFieldKredit.equals("") ||
                    Integer.parseInt(dataRekening[0]) - Integer.parseInt(jTextFieldKredit.getText()) < 0 ||
                    Integer.parseInt(jTextFieldKredit.getText()) + totalTransaksi > 5000000 ||
                    Integer.parseInt(dataRekening[0]) < 50000){
                KreditGagal();
            }else{
                int jmlKredit = Integer.parseInt(jTextFieldKredit.getText());
                transKre.setKredit(jmlKredit, teller_ktp);
                KreditBerhasil();
                Kredit k = new Kredit();
        k.setVisible(true);
        this.setVisible(false);
            }
        }else if(dataRekening[3].equals("Bisnis")){
            if(jTextFieldKredit.equals("") ||
                    Integer.parseInt(dataRekening[0]) - Integer.parseInt(jTextFieldKredit.getText()) < 0 ||
                    Integer.parseInt(jTextFieldKredit.getText()) + totalTransaksi > 5000000 ||
                    Integer.parseInt(dataRekening[0]) < 150000){
                KreditGagal();
            }else{
                int jmlKredit = Integer.parseInt(jTextFieldKredit.getText());
                transKre.setKredit(jmlKredit, teller_ktp);
            }
        }
        
    }//GEN-LAST:event_jButtonProsesActionPerformed

    private void jButtonCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCariActionPerformed
        // TODO add your handling code here:
        CariRekening cariRek = new CariRekening();
        int noRek = Integer.parseInt(jTextFieldCari.getText());

        cariRek.setRekNasabah(noRek);

        String dataRekening[] = cariRek.getRekening();
        String dataNasabah[] = cariRek.getNasabah();

        try{
            jTextFieldNama.setText(dataNasabah[1]);
            jTextFieldJenis.setText(dataRekening[3]);
            jTextFieldSaldo.setText(dataRekening[0]);
            if(jTextFieldJenis.getText().equals("Biasa")){
                jTextFieldSisa.setText(Integer.toString(5000000-totalTransaksi));
                System.out.println(totalTransaksi);
            }
            else if(jTextFieldJenis.getText().equals("Bisnis")){
                jTextFieldSisa.setText("50000000");
            }
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButtonCariActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        // TODO add your handling code here:
        Dashboard d = new Dashboard();
        d.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kredit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kredit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kredit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kredit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kredit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonCari;
    private javax.swing.JButton jButtonProses;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextFieldCari;
    private javax.swing.JTextField jTextFieldJenis;
    private javax.swing.JTextField jTextFieldKredit;
    private javax.swing.JTextField jTextFieldNama;
    private javax.swing.JTextField jTextFieldSaldo;
    private javax.swing.JTextField jTextFieldSisa;
    private javax.swing.JTextField jTextFieldTanggal;
    private javax.swing.JTextField jTextFieldTeller;
    // End of variables declaration//GEN-END:variables
}
