/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jFrame;

import java.io.File;
import javaClass.CariRekening;
import javaClass.TransaksiRek;
import java.sql.Connection;
import java.sql.ResultSet;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.HashMap;
import java.util.Map;
import javaClass.KoneksiDB;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel; 
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author User
 */
public class Rekening extends javax.swing.JFrame {

    private DefaultTableModel model;
    String teller_nama = Dashboard.teller_nama;
    //int teller_ktp = Login.teller_ktp;
    int teller_ktp = 1635;
    int totalTransaksi;
    int rekening_nomor;
    
    JasperDesign jasperDesign;
    JasperReport jasperReport;
    JasperPrint jasperPrint;
    Map<String, Object> param = new HashMap<String, Object>();
    /**
     * Creates new form Rekening
     */
    public Rekening() {
        initComponents();
        setLocationRelativeTo(null);
        model = new DefaultTableModel();
        jTableTransaksi.setModel(model);
        model.addColumn("Nomor Transaksi");
        model.addColumn("Tanggal Transaksi");
        model.addColumn("Jenis Transaksi");
        model.addColumn("Jumlah Transaksi");  
        setForm();
    }
    
    public void setForm(){
        jTextFieldTeller.setText(Integer.toString(teller_ktp));
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd");
        LocalDateTime currentDate = LocalDateTime.now();
        jTextFieldTanggal.setText(dtf.format(currentDate));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldCari = new javax.swing.JTextField();
        jButtonCari = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldJenis = new javax.swing.JTextField();
        jTextFieldNoRek = new javax.swing.JTextField();
        jTextFieldNama = new javax.swing.JTextField();
        jTextFieldTTL = new javax.swing.JTextField();
        jTextFieldAlamat = new javax.swing.JTextField();
        jTextFieldSaldo = new javax.swing.JTextField();
        jTextFieldPoin = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTransaksi = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldTeller = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldTanggal = new javax.swing.JTextField();
        jButtonCetak = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1366, 768));
        setSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Nomor Rekening");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 160, 131, 22);

        jTextFieldCari.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jTextFieldCari);
        jTextFieldCari.setBounds(340, 160, 100, 28);

        jButtonCari.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonCari.setText("Cari");
        jButtonCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCariActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCari);
        jButtonCari.setBounds(460, 161, 100, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Data Nasabah");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(560, 100, 150, 29);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Jenis Rekening");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(110, 200, 117, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Nomor Rekening");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(110, 240, 131, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Nama");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(110, 280, 45, 22);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("TTL");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(110, 320, 31, 22);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Alamat");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(110, 360, 54, 22);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Saldo");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(110, 400, 170, 14);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Poin");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(110, 430, 130, 14);

        jTextFieldJenis.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jTextFieldJenis);
        jTextFieldJenis.setBounds(350, 200, 142, 28);

        jTextFieldNoRek.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jTextFieldNoRek);
        jTextFieldNoRek.setBounds(350, 240, 142, 28);

        jTextFieldNama.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jTextFieldNama);
        jTextFieldNama.setBounds(350, 280, 142, 28);

        jTextFieldTTL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jTextFieldTTL);
        jTextFieldTTL.setBounds(350, 320, 142, 28);

        jTextFieldAlamat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jTextFieldAlamat);
        jTextFieldAlamat.setBounds(350, 360, 142, 28);

        jTextFieldSaldo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jTextFieldSaldo);
        jTextFieldSaldo.setBounds(350, 390, 142, 28);

        jTextFieldPoin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jTextFieldPoin);
        jTextFieldPoin.setBounds(350, 430, 142, 28);

        jTableTransaksi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTableTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableTransaksi);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(750, 220, 452, 248);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Laporan Transaksi");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(750, 200, 143, 22);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("ID Teller");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(930, 100, 68, 22);

        jTextFieldTeller.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jTextFieldTeller);
        jTextFieldTeller.setBounds(1010, 100, 61, 28);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Tanggal");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(1080, 100, 63, 22);

        jTextFieldTanggal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jTextFieldTanggal);
        jTextFieldTanggal.setBounds(1150, 100, 101, 28);

        jButtonCetak.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonCetak.setText("Cetak");
        jButtonCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCetakActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCetak);
        jButtonCetak.setBounds(1121, 172, 110, 31);

        jButton1.setText("Kembali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(1110, 530, 89, 29);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCariActionPerformed
        // TODO add your handling code here:
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged(); 
        
        TransaksiRek transRek = new TransaksiRek();
        transRek.setTransaksi(Integer.parseInt(jTextFieldCari.getText()));
        ResultSet rs = transRek.getTabelTransaksi();
        try{
            if(rs.next()==false){
                JOptionPane.showMessageDialog(this, "Nomor rekening tidak ditemukan");
            }else{
                rekening_nomor = Integer.parseInt(jTextFieldCari.getText());
                jTextFieldNoRek.setText(jTextFieldCari.getText());
            }   
        }catch(Exception e){
            System.out.println(e);
        }
        
        CariRekening rekNasabah = new CariRekening();
        rekNasabah.setRekNasabah(Integer.parseInt(jTextFieldCari.getText()));
        String dataNasabah[] = rekNasabah.getNasabah();
        String dataRekening[] = rekNasabah.getRekening();
        
        try{
            
            jTextFieldJenis.setText(dataRekening[3]);
            jTextFieldNama.setText(dataNasabah[1]);
            jTextFieldTTL.setText(dataNasabah[2]);
            jTextFieldAlamat.setText(dataNasabah[3]);
            jTextFieldSaldo.setText(dataRekening[0]);
            jTextFieldPoin.setText(dataRekening[2]);
            
            while(rs.next()){
                
                Object[] obj = new Object[4];
                
                obj[0] = rs.getInt("transaksi_nomor");
                obj[1] = rs.getDate("transaksi_tanggal");
                obj[2] = rs.getString("transaksi_jenis");
                obj[3] = rs.getInt("transaksi_nominal");
                model.addRow(obj);    
                
                
                
                    
                    
            }
        }catch(Exception e){
            System.out.println(e);
        }
        
        
    }//GEN-LAST:event_jButtonCariActionPerformed

    private void jButtonCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCetakActionPerformed
        // TODO add your handling code here:
        try{
            File file = new File("src/jFrame/transaksiNasabah.jrxml");
            jasperDesign = JRXmlLoader.load(file);
            param.clear(); 
            param.put("rekening_nomor", rekening_nomor);
            jasperReport = JasperCompileManager.compileReport(jasperDesign);
            jasperPrint = JasperFillManager.fillReport(jasperReport, param, KoneksiDB.getKoneksi());
            JasperViewer.viewReport(jasperPrint, false);
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButtonCetakActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
Dashboard d = new Dashboard();
        d.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rekening.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rekening.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rekening.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rekening.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rekening().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCari;
    private javax.swing.JButton jButtonCetak;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableTransaksi;
    private javax.swing.JTextField jTextFieldAlamat;
    private javax.swing.JTextField jTextFieldCari;
    private javax.swing.JTextField jTextFieldJenis;
    private javax.swing.JTextField jTextFieldNama;
    private javax.swing.JTextField jTextFieldNoRek;
    private javax.swing.JTextField jTextFieldPoin;
    private javax.swing.JTextField jTextFieldSaldo;
    private javax.swing.JTextField jTextFieldTTL;
    private javax.swing.JTextField jTextFieldTanggal;
    private javax.swing.JTextField jTextFieldTeller;
    // End of variables declaration//GEN-END:variables
}
