/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jFrame;

import javaClass.KoneksiDB;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Teller extends javax.swing.JFrame {

    /**
     * Creates new form Teller
     */
    public Teller() {
        initComponents();
        setLocationRelativeTo(null);
        jButtonDelete.setEnabled(false);
        jButtonEdit.setEnabled(false);
        jButtonCancel.setEnabled(false);
    }
    
    int teller_ktp;
    String teller_nama;
    String teller_username;
    String teller_password;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButtonBack = new javax.swing.JButton();
        jButtonReset = new javax.swing.JButton();
        jButtonCreate = new javax.swing.JButton();
        jButtonEdit = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jTextFieldKtp = new javax.swing.JTextField();
        jTextFieldNama = new javax.swing.JTextField();
        jTextFieldUsername = new javax.swing.JTextField();
        jTextFieldPassword = new javax.swing.JTextField();
        jTextFieldConfirm = new javax.swing.JTextField();
        jTextFieldCari = new javax.swing.JTextField();
        jButtonCari = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1366, 768));
        setSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(null);

        jLabel1.setText("No. KTP");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(530, 240, 70, 14);

        jLabel2.setText("Nama");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(530, 290, 50, 14);

        jLabel3.setText("Username");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(520, 340, 70, 20);

        jLabel4.setText("Password");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(520, 400, 60, 20);

        jLabel5.setText("Confirm");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(510, 460, 60, 14);

        jButtonBack.setText("Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBack);
        jButtonBack.setBounds(730, 540, 90, 30);

        jButtonReset.setText("Reset");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonReset);
        jButtonReset.setBounds(620, 540, 90, 30);

        jButtonCreate.setText("Create");
        jButtonCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCreate);
        jButtonCreate.setBounds(510, 540, 90, 30);

        jButtonEdit.setText("Edit");
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEdit);
        jButtonEdit.setBounds(510, 580, 90, 30);

        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDelete);
        jButtonDelete.setBounds(620, 580, 90, 30);
        getContentPane().add(jTextFieldKtp);
        jTextFieldKtp.setBounds(630, 240, 142, 20);
        getContentPane().add(jTextFieldNama);
        jTextFieldNama.setBounds(630, 290, 142, 20);
        getContentPane().add(jTextFieldUsername);
        jTextFieldUsername.setBounds(630, 340, 142, 20);
        getContentPane().add(jTextFieldPassword);
        jTextFieldPassword.setBounds(630, 400, 142, 20);
        getContentPane().add(jTextFieldConfirm);
        jTextFieldConfirm.setBounds(630, 460, 142, 20);

        jTextFieldCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCariActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCari);
        jTextFieldCari.setBounds(530, 180, 142, 20);

        jButtonCari.setText("Cari");
        jButtonCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCariActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCari);
        jButtonCari.setBounds(700, 180, 70, 23);

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancel);
        jButtonCancel.setBounds(730, 580, 90, 30);

        jLabel6.setText("TAMBAH TELLER");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(590, 100, 190, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        // TODO add your handling code here:
        Dashboard dashboard = new Dashboard();
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jTextFieldCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCariActionPerformed
        // TODO add your handling code here:     
        
    }//GEN-LAST:event_jTextFieldCariActionPerformed

    private void jButtonCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCariActionPerformed
        // TODO add your handling code here:
        try{
            teller_ktp = Integer.parseInt(jTextFieldCari.getText());
            Connection koneksi = KoneksiDB.getKoneksi();
            Statement s = koneksi.createStatement();
            String sql = "SELECT * FROM teller WHERE teller_ktp ="+this.teller_ktp;
            ResultSet rs = s.executeQuery(sql);
            while(rs.next()){
                teller_nama = rs.getString("teller_nama");
                teller_username = rs.getString("teller_username");
                teller_password = rs.getString("teller_password");
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Teller tidak ditemukan");
        }
        
        jTextFieldKtp.setText(Integer.toString(teller_ktp));
        jTextFieldNama.setText(teller_nama);
        jTextFieldUsername.setText(teller_username);
        jTextFieldPassword.setText(teller_password);
        jTextFieldConfirm.setText("");
        
        jButtonCreate.setEnabled(false);
        jButtonEdit.setEnabled(true);
        jButtonDelete.setEnabled(true);
        jButtonCancel.setEnabled(true);
        
    }//GEN-LAST:event_jButtonCariActionPerformed

    private void jButtonCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateActionPerformed
        // TODO add your handling code here:
        if(jTextFieldNama.getText().equals("") || jTextFieldKtp.getText().equals("") || jTextFieldUsername.getText().equals("") || jTextFieldPassword.getText().equals("") || jTextFieldConfirm.getText().equals("") ){
            JOptionPane.showMessageDialog(this, "Data teller masing kosong");
        }else{
            if(jTextFieldPassword.getText().equals(jTextFieldConfirm.getText())){
                try{
                teller_ktp = Integer.parseInt(jTextFieldKtp.getText());
                teller_nama = jTextFieldNama.getText();
                teller_username = jTextFieldUsername.getText();
                teller_password = jTextFieldPassword.getText();

                Connection koneksi = KoneksiDB.getKoneksi();
                Statement s = koneksi.createStatement();
                String sql = "INSERT INTO teller(teller_ktp, teller_nama, teller_username, teller_password) VALUES (?, ?, ?, ?)";
                PreparedStatement p = koneksi.prepareStatement(sql);     

                p.setInt(1, teller_ktp);
                p.setString(2, teller_nama);
                p.setString(3, teller_username);
                p.setString(4, teller_password);

                p.executeUpdate();
                p.close();

                JOptionPane.showMessageDialog(null, "Akun Teller berhasil dibuat");

                }catch(SQLException e){
                    System.out.println(e);
                    System.out.println("error");
                }
            }else{
                JOptionPane.showMessageDialog(null, "Password doesn't match");
            }
        }
    }//GEN-LAST:event_jButtonCreateActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        // TODO add your handling code here:
        jTextFieldKtp.setText("");
        jTextFieldNama.setText("");
        jTextFieldUsername.setText("");
        jTextFieldPassword.setText("");
        jTextFieldConfirm.setText("");
    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
        // TODO add your handling code here:
        if(jTextFieldPassword.getText().equals(jTextFieldConfirm.getText())){
            try{
                teller_ktp = Integer.parseInt(jTextFieldKtp.getText());
                teller_nama = jTextFieldNama.getText();
                teller_username = jTextFieldUsername.getText();
                teller_password = jTextFieldPassword.getText();

                Connection koneksi = KoneksiDB.getKoneksi();
                Statement s = koneksi.createStatement();
                String sql = "UPDATE teller SET teller_nama = ?, teller_username = ?, teller_password = ? WHERE teller_ktp = ?";
                PreparedStatement p = koneksi.prepareStatement(sql);     

                p.setString(1, teller_nama);
                p.setString(2, teller_username);
                p.setString(3, teller_password);
                p.setInt(4, teller_ktp);

                p.executeUpdate();
                p.close();

                JOptionPane.showMessageDialog(null, "Akun Teller berhasil diubah");
                
                jButtonCreate.setEnabled(true);
                jButtonCancel.setEnabled(false);
                jButtonDelete.setEnabled(false);
                jButtonEdit.setEnabled(false);
                
                
            }catch(SQLException e){
                System.out.println(e);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Password doesn't match");
        }
    }//GEN-LAST:event_jButtonEditActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:
        int hapus = JOptionPane.showOptionDialog(this, 
                    "Yakin ingin menghapus data teller?", 
                    "Hapus Data Teller", 
                    JOptionPane.YES_NO_OPTION, 
                    JOptionPane.QUESTION_MESSAGE, null, null, null);
    
        if(hapus == JOptionPane.YES_OPTION){
            try{

                Connection koneksi = KoneksiDB.getKoneksi();
                Statement s = koneksi.createStatement();
                String sql = "DELETE FROM teller WHERE teller_ktp = ?";
                PreparedStatement p = koneksi.prepareStatement(sql);     
                p.setInt(1, teller_ktp);
                p.executeUpdate();
                p.close();

                JOptionPane.showMessageDialog(null, "Akun Teller berhasil dihapus");
                
                jTextFieldCari.setText("");
                jTextFieldKtp.setText("");
                jTextFieldNama.setText("");
                jTextFieldUsername.setText("");
                jTextFieldPassword.setText("");
                
                jButtonCreate.setEnabled(true);
                jButtonCancel.setEnabled(false);
                jButtonDelete.setEnabled(false);
                jButtonEdit.setEnabled(false);
                
            }catch(SQLException e){
                    System.out.println(e);
                    System.out.println("error");
            }
        }
        
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // TODO add your handling code here:
        jTextFieldCari.setText("");
        jTextFieldKtp.setText("");
        jTextFieldNama.setText("");
        jTextFieldUsername.setText("");
        jTextFieldPassword.setText("");
        
        jButtonCreate.setEnabled(true);
        jButtonDelete.setEnabled(false);
        jButtonEdit.setEnabled(false);
        jButtonCancel.setEnabled(false);
    }//GEN-LAST:event_jButtonCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Teller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Teller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Teller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Teller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Teller().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonCari;
    private javax.swing.JButton jButtonCreate;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextFieldCari;
    private javax.swing.JTextField jTextFieldConfirm;
    private javax.swing.JTextField jTextFieldKtp;
    private javax.swing.JTextField jTextFieldNama;
    private javax.swing.JTextField jTextFieldPassword;
    private javax.swing.JTextField jTextFieldUsername;
    // End of variables declaration//GEN-END:variables
}
